// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApJsHC9b9Kk2_sCz4_lr2CXY178YEHxhQ',
    appId: '1:699607110047:web:3504efa765f1cd2005adaa',
    messagingSenderId: '699607110047',
    projectId: 'tutorhub-e5cd0',
    authDomain: 'tutorhub-e5cd0.firebaseapp.com',
    storageBucket: 'tutorhub-e5cd0.appspot.com',
    measurementId: 'G-E1YNMRN0WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuEX69nrkWjZxpaTi1AjZBV-AqAgeCuKo',
    appId: '1:699607110047:android:9ee5c967ff4ee70b05adaa',
    messagingSenderId: '699607110047',
    projectId: 'tutorhub-e5cd0',
    storageBucket: 'tutorhub-e5cd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8LJDvpgRW1wDy9gXn3wo56DpK5pRGN_0',
    appId: '1:699607110047:ios:e5ebffecd77f711805adaa',
    messagingSenderId: '699607110047',
    projectId: 'tutorhub-e5cd0',
    storageBucket: 'tutorhub-e5cd0.appspot.com',
    iosBundleId: 'com.example.tutorhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8LJDvpgRW1wDy9gXn3wo56DpK5pRGN_0',
    appId: '1:699607110047:ios:31fd15899878a9e305adaa',
    messagingSenderId: '699607110047',
    projectId: 'tutorhub-e5cd0',
    storageBucket: 'tutorhub-e5cd0.appspot.com',
    iosBundleId: 'com.example.tutorhub.RunnerTests',
  );
}
